### ISSUE TITLE
Build error on master

### ISSUE THREAD

**Issue by barthogenes** [pavelyazev/gr-dect2#14]
Hello, I am trying to get this module to work on `Ubuntu 20.04.3 LTS` but I get the following error when I run the `make` command:

```bash
gnuradio@flinn git:(master*):~/gr-dect2/build >> make
Scanning dependencies of target gnuradio-dect2
[ 16%] Building CXX object lib/CMakeFiles/gnuradio-dect2.dir/phase_diff_impl.cc.o
/home/gnuradio/gr-dect2/lib/phase_diff_impl.cc: In static member function ‘static gr::dect2::phase_diff::sptr gr::dect2::phase_diff::make()’:
/home/gnuradio/gr-dect2/lib/phase_diff_impl.cc:38:9: error: could not convert ‘gnuradio::get_initial_sptr(T*) [with T = gr::dect2::phase_diff_impl]()’ from ‘std::shared_ptr<gr::dect2::phase_diff_impl>’ to ‘gr::dect2::phase_diff::sptr’ {aka ‘boost::shared_ptr<gr::dect2::phase_diff>’}
   37 |       return gnuradio::get_initial_sptr
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~
   38 |         (new phase_diff_impl());
      |         ^~~~~~~~~~~~~~~~~~~~~~~
      |         |
      |         std::shared_ptr<gr::dect2::phase_diff_impl>
make[2]: *** [lib/CMakeFiles/gnuradio-dect2.dir/build.make:63: lib/CMakeFiles/gnuradio-dect2.dir/phase_diff_impl.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:248: lib/CMakeFiles/gnuradio-dect2.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Am I doing something wrong?

**Comment by Bernadetten** [comment]
Have you found an answer?

**Comment by pavelyazev** [comment]
It was incompatibility with the updated Gnuradio. Please try with the last commit.

**Comment by Bernadetten** [comment]
Thank you for your answer, I did indeed figure it out too. I solved it by using it on older version of GNUradio. :D
